python/inflean/kilogram/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name ='kilogram'

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name = 'index'),
    url(r'^upload$', views.upload, name = 'upload'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile_update/$',login_required(views.ProfileUpdateView.as_view()),
        name='profile_update'),
]

python/inflean/lotto/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

#views가 lotto라는 폴더(모듈)의 views다

app_name= 'lotto'
urlpatterns = [
    url(r'^$', views.index, name='index'), 
    url(r'^new/$', views.post, name="new_lotto"),
    url(r'^(?P<lottokey>[0-9]+)/detail/$', views.detail, name='detail'),
    	]
    #^$아무것도 없는 url(기본 유알엘)

python/inflean/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from polls import views
from kilogram import views as kilogram_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^lotto/', include('lotto.urls')),
    url(r'^$', login_required(kilogram_views.IndexView.as_view()), name = 'root'),
    url(r'^kilogram/', include('kilogram.urls')),
    url(r'^accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

python/inflean/kilogram/models.py
from django.db import models
from django.conf import settings
from sorl.thumbnail import ImageField

# Create your models here.

def user_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    # honux/absdfer.png
    return '%s/%s.%s' % (instance.owner.username, pid, extension)


class Photo(models.Model):
    image = models.ImageField(upload_to = user_path)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    comment = models.CharField(max_length = 255)
    pub_date = models.DateTimeField(auto_now_add = True)
    is_public = models.BooleanField(default=False)

    def __str__(self):
        return '{} {} {}'.format(self.owner.username, self.comment, self.is_public)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    nickname = models.CharField(max_length=64)
    profile_photo = models.ImageField(blank=True)

python/inflean/kilogram/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import Photo, Profile

class UploadForm(forms.ModelForm):
    comment = forms.CharField(max_length=255)
    class Meta:
        model = Photo
        exclude = ('thumnail_image', 'owner')

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name',]

class ProfileForm(forms.ModelForm):
    profile_photo = forms.ImageField(required=False)

    class Meta:
        model = Profile
        fields = ['nickname', 'profile_photo']

python/inflean/kilogram/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .forms import UploadForm, UserForm, ProfileForm
from .models import Profile
# Create your views here.

@login_required
def upload(request):
    if request.method == "POST":
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit = False)
            photo.owner = request.user
            form.save()
            return redirect('kilogram:index')

    form = UploadForm()
    return render(request, 'kilogram/upload.html', {'form': form})

class IndexView(ListView):
    # model = Photo
    context_object_name = 'user_photo_list'
    paginate_by = 2

    def get_queryset(self):
        user = self.request.user
        return user.photo_set.all().order_by('-pub_date')

@login_required
def profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    photos = user.photo_set.filter(is_public=True)[:20]
    context = {"profile_user": user, "photos": photos}
    return render(request, 'kilogram/profile.html', context)


class ProfileUpdateView(View):
    def get(self, request):
        user = get_object_or_404(User, pk=request.user.pk)

        user_form = UserForm(initial={
            'first_name': user.first_name,
            'last_name': user.last_name,
        })

        if hasattr(user, 'profile'):
            profile = user.profile
            profile_form = ProfileForm(initial={
                'nickname': profile.nickname,
                'profile_photo': profile.profile_photo,
            })
        else:
            profile_file = ProfileForm()

        return render(request, 'kilogram/profile_update.html',
            {"user_form": user_form, "profile_form": profile_form})

    def post(self, request):
        pk = request.user.pk
        u = User.objects.get(id=pk)
        user_form = UserForm(request.POST, instance=u)

        if (user_form.is_valid()):
            user_form.save()

        if hasattr(u, 'profile'):
            profile = u.profile
            profile_form = ProfileForm(request.POST, request.FILES,
                instance=profile)
        else:
            profile_form = ProfileForm(request.POST, request.FILES)

        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = u
            profile.save()

        return redirect('kilogram:profile', pk)

python/inflean/kilogram/templates/kilogram/photo_list.html
{% extends 'account/base.html' %}
{% block content %}

<p> <a class="btn btn-primary" href="{% url 'kilogram:upload'%}">업로드</a></p>

  {% if user_photo_list %}
  {% for photo in user_photo_list %}
  <div class="panel panel-default" align="center">
    <div class="panel-heading"><h4>{{photo.owner.username}}</h4></div>
    <div class="panel-body">
      {% if photo.image.width > 800 %}
      <p><img src = '{{photo.image.url}}' width='600' /> <br>
        {% else %}
        <p><img src = '{{photo.image.url}}' /> <br>
          {% endif %}
          {{photo.comment}}</p>
      </div>
    </div>
      {% endfor %}
      {% else %}
      <h4>아직 사진이 없네요. 첫번째 사진을 업로드하세요!</h4>
      {% endif %}

    <!-- pagenation nav -->
    {% if is_paginated %}
    <nav aria-label="...">
        <ul class="pager">
          {% if page_obj.has_previous %}
          <li><a href="{%url 'kilogram:index'%}?page={{ page_obj.previous_page_number }}">이전</a></li>
          {% endif %}
          <li> <a href="#">페이지 {{ page_obj.number }} / {{ page_obj.paginator.num_pages }} </a></li>
          {% if page_obj.has_next %}
          <li>
            <a href="{%url 'kilogram:index'%}?page={{ page_obj.next_page_number }}">다음</a>
          </li>
          {% endif %}
        </ul>
    </nav>
    {% endif %}

{% endblock %}

python/inflean/kilogram/templates/kilogram/profile.html
{% extends 'account/base.html' %}
{% block content %}

{% load staticfiles %}
{% load thumbnail %}

<div class="row">
    <div class="col-xs-6 col-md-3">
        {% if profile_user.profile.profile_photo %}
        <img class="round" src="{{profile_user.profile.profile_photo.url}}" width="200"> <br>
        {% else %}
        <img class="round" src="{% static 'kilogram/images/photo.jpg' %}" width="200"> <br>
        {% endif %}
    </div>

    <div class="col-xs-6 col-md-3">
        {% if profile_user.profile.nickname %}
        <h2>{{profile_user.profile.nickname}}</h2>
        {% endif %}
        {% if user == profile_user %}
        <a href="{% url 'kilogram:profile_update' %}">
            <button type="button" class="btn btn-default">프로필 편집</button></a></h2>
        {% endif %}
        <h3> {{profile_user.username}} <br>
            {% if profile_user.first_name is not None %}
            {{profile_user.first_name}} {{profile_user.last_name}} <br>
            {% endif %}
        </h3>
    </div>
</div> <!-- endof row -->
<div class="row">
  {%for photo in photos %}
  <div class="col-xs-6 col-md-4">
      {% thumbnail photo.image "300x300" crop="center" as im %}
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %}
  </div>
  {% endfor %}
</div>

{% endblock %}

python/inflean/kilogram/templates/kilogram/profile_update.html
{% extends 'account/base.html' %}
{% block content %}

<h1>{{user.username}} Profile Update</h1>

    {% if error_msg %}
    <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Error</strong> {{error_msg}}
    </div>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Update" />
    </form>
</p>

{% endblock %}

python/inflean/kilogram/templates/kilogram/upload.html
{% extends 'account/base.html' %}
{% block content %}

<h1>Kilogram Image Upload</h1>

<form action="{% url 'kilogram:upload'%}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Upload">
</form>

{% endblock %}