python/askdjango/askdjango/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.views.generic import RedirectView


# def root(request):
#     return redirect('blog:post_list')

urlpatterns = [
    # url(r'^$', root, name='root'),
    url(r'^$', lambda r: redirect('blog:post_list'), name='root'),
    # url(r'^$', RedirectView.as_view(pattern_name='blog:post_list')),

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

python/askdjango/blog/urls.py
# blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<id>\d+)/$', views.post_detail, name='post_detail'),

    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),

    url(r'^cbv/new/$', views_cbv.post_new),
]

python/askdjango/blog/models.py
# blog/models.py
import re
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.forms import ValidationError
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail


def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')


class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100, verbose_name='제목',
        help_text='포스팅 제목을 입력해주세요. 최대 100자 내외.')  # 길이 제한이 있는 문자열
    content = models.TextField(verbose_name='내용')              # 길이 제한이 없는 문자열

    photo = ProcessedImageField(blank=True, upload_to='blog/post/%Y/%m/%d',
            processors=[Thumbnail(300,300)],
            format='JPEG',
            options={'quality':60})

    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=50, blank=True,
        validators=[lnglat_validator],
        help_text='경도/위도 포맷으로 입력')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    tag_set = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

python/askdjango/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

python/askdjango/blog/views.py
# blog/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post
from .forms import PostForm


def post_list(request):
    qs = Post.objects.all()

    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(title__icontains=q)

    # messages.error(request, '에러메세지 테스트')

    return render(request, 'blog/post_list.html', {
        'post_list': qs,
        'q': q,
    })


def post_detail(request, id):
#   try:
#       post = Post.objects.get(id=id)
#   except Post.DoesNotExist:
#       raise Http404
    
    post = get_object_or_404(Post, id=id)

    return render(request, 'blog/post_detail.html', {
        'post': post,
    })


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, '새 포스팅을 저장했습니다.')
            return redirect(post)  # post.get_absolute_url() => post detail
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form,
    })


def post_edit(request, id):
    post = get_object_or_404(Post, id=id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, '포스팅을 수정했습니다.')
            return redirect(post)  # post.get_absolute_url() => post detail
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form': form,
    })

python/askdjango/blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block title %}AskDjango's Blog{% endblock %}

python/askdjango/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load imagekit %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>{{ post.title }}</h2>

                {# <img src="/media/{{ post.photo }}" style="max-width: 100%;" /> #}
                {% if post.photo %}
                    <img src="{{ post.photo.url }}" style="max-width: 100%;" />

                    {% thumbnail "100x100" post.photo %}


                    {% thumbnail "100x100" post.photo as thumb %}
                    <!-- thumbnail custum화 하기 -->
                    <img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" />

                    {% thumbnail "100x100" post.photo -- style="" onclick="" class=""%}
   
                {% endif %}

                {{ post.content|linebreaks }}

                <hr/>

                <h3>Comments</h3>

                <ul>
                {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.message }}
                        <small>by {{ comment.author }}</small>
                        <small>at {{ comment.updated_at }}</small>kk
                    </li>
                {% endfor %}
                </ul>

                <hr/>
                <a href="{% url "blog:post_list" %}" class="btn btn-primary">글 목록</a>
                <a href="{% url "blog:post_edit" post.id %}" class="btn btn-default">수정</a>
            </div>
        </div>
    </div>
{% endblock %}

python/askdjango/blog/templates/blog/post_form.html
<!-- blog/templates/blog/post_form.html -->

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

python/askdjango/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Django Template <sup>by AskDjango</sup></h1>
            <p>여러분의 파이썬/장고 페이스메이커가 되어드리겠습니다.</p>
            <p>
                <a class="btn btn-lg btn-primary" href="http://facebook.com/groups/askdjango">
                        AskDjango 페이스북 그룹 &raquo;
                    </a>
            </p>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-info">
                    <ul>
                    <li>http://localhost:8000/blog/ 주소로 접속해보세요.</li>
                    <li>템플릿 경로를 blog/templates/post_list.html 경로가 아닌
                    blog/ templates/blog/post_list.html 경로를 쓰는 지에 대한 이유는,
                    후에 Template Loader에서 설명합니다.</li>
                    </ul>
                </div>

                <a href="{% url "blog:post_new" %}" class="btn btn-primary pull-right">New Post</a>

                <p>
                    <form action="" method="get">
                        <input type="text" name="q" value="{{ q }}" />
                        <input type="submit" value="검색" class="btn btn-primary" />
                    </form>
                </p>
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>title</th>
                            <th>author</th>
                            <th>updated_at</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in post_list %}
                            <tr>
                                <td>{{ post.id }}</td>
                                <td><a href="{% url "blog:post_detail" post.id %}">{{ post.title }}</a></td>
                                <td><small>by {{ post.author }}</small></td>
                                <td><small>at {{ post.updated_at }}</small></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>


{% endblock %}