python/inflean/lotto/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

#views가 lotto라는 폴더(모듈)의 views다

app_name= 'lotto'
urlpatterns = [
    url(r'^$', views.index, name='index'), 
    url(r'^new/$', views.post, name="new_lotto"),
    url(r'^(?P<lottokey>[0-9]+)/detail/$', views.detail, name='detail'),
    	]
    #^$아무것도 없는 url(기본 유알엘)

python/inflean/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from polls import views
from kilogram import views as kilogram_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^lotto/', include('lotto.urls')),
    url(r'^$', login_required(kilogram_views.IndexView.as_view()), name = 'root'),
    url(r'^kilogram/', include('kilogram.urls')),
    url(r'^accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

python/inflean/lotto/models.py
from django.db import models
from django.utils import timezone #장고 유틸에 타임존 있음
import random

# Create your models here.
class GuessNumbers(models.Model):
	# 하위클래스		슈퍼클래스(상위클래스)
	# 변수선언하기		캐릭터필드
	name=models.CharField(max_length = 24)
	lottos=models.CharField(max_length = 255, default = '[1,2,3,4,5,6]')
	text=models.CharField(max_length = 255)
	num_lotto = models.IntegerField(default = 5)
	update_date = models.DateTimeField()

# 로토 번호 생성 및 데이터베이스 저장
	def generate(self):
		self.lottos = ""
		origin = list(range(1,46))
		for _ in range(0, self.num_lotto):
			random.shuffle(origin)
			guess = origin[:6]
			guess.sort()
			self.lottos += str(guess) +'\n'
		self.update_date = timezone.now()
		self.save() #object를 데이터에 저장

	def __str__(self):
		return "%s %s" % (self.name, self.text)

python/inflean/lotto/forms.py
from django import forms
from .models import GuessNumbers

class PostForm(forms.ModelForm):

	class Meta:
		model=GuessNumbers
		fields = ('name', 'text',)

python/inflean/lotto/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import GuessNumbers
from .forms import PostForm


def index(request):
		# 리케스트 받아서
	lottos=GuessNumbers.objects.all()

	# 브라우저의 리퀘스트를 받아와서 그대로 전달해주는데 템플릿에 전달해준다 추가적으로 오브젝트를 보여주는데 빈오브젝트임
	return render(request, "lotto/default.html",{"lottos":lottos})
				# 리케스트 전달, 템플릿으로,			빈오브젝트

def post(request):
	if request.method =="POST":
		#save data
		form = PostForm(request.POST)
		if form.is_valid():
			lotto = form.save(commit=False)
			lotto.generate()
			return redirect('lotto:index')# 메인으로 가는 name
	else:
		form = PostForm()
		return render(request, "lotto/form.html", {"form":form})

def detail(request, lottokey):
	lotto=GuessNumbers.objects.get(pk=lottokey)
	return render(request,"lotto/detail.html",{"lotto":lotto})

python/inflean/lotto/templates/lotto/default.html
<!-- lotto/template/lotto/default.html -->
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ko">
<head>
  <title>My Little Lotto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="{% static 'css/lotto.css'%}">
  <link href="//fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
</head>

<body>
  <div class="page-header">
  <h1><a href="{% url 'lotto:index'%}">My Lotto Page</a></h1>
  <a href="{% url 'lotto:new_lotto' %}"><span class="glyphicon glyphicon-plus btn btn-default"></span></a></h1>
  </div>
  <div class="container lotto">
    {% for lotto in lottos%}
    <h2><a href="{% url 'lotto:detail' lottokey=lotto.pk %}">{{lotto.text}}</a></h2>
    <p> last update: {{lotto.update_date}} by {{lotto.name}}</p>
    <p> {{lotto.lottos|linebreaksbr}}</p>
    {% endfor %}
  </div>
</body>
</html>

python/inflean/lotto/templates/lotto/detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ko">
<head>
  <title>My Little Lotto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="//fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/lotto.css'%}">
</head>

<body>
  <div class="page-header">
  <h1><a href="{% url 'lotto:index'%}">My Lotto Page</a></h1>
  <h2><a href="{% url 'lotto:new_lotto'%}">
    <span class="glyphicon glyphicon-plus btn btn-default"></span></a></h2>
  </div>
  <div class="container lotto">
    <h2>{{lotto.text}}</h2>
    <p> by {{lotto.name}}</p>
    <p> {{lotto.update_date}}</p>
    <p> {{lotto.lottos|linebreaksbr}}</p>
  </div>
</body>
</html>

python/inflean/lotto/templates/lotto/form.html
<!DOCTYPE html> {% load staticfiles %}
<html lang="ko">
 <head>
  <title>My Little Lotto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="//fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/lotto.css' %}"> 
 </head>
 <body>
  <div class="page-header">
   <h1>My Little New Lotto</h1>
  </div>
  <div class="container lotto">           <!-- 보안땜에 -->
   <form method="POST" class="post-form">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Save</button> </form>
  </div>
 </body>
</html>